### ISSUE TITLE
Context cleanup blocking on Windows

### ISSUE THREAD

**Issue by abravalheri** [fagg/matlab-zmq#22]
Hi @fagg , could you please verify if the following commands lead MATLAB to blocking state also in OS X?

```matlab
context = zmq.Context();
socket = context.socket('ZMQ_PUB');
clear('context');
```

On Windows, I'm facing this problem, maybe it would be necessary to keep a track on opened sockets and close them before shutting down context...

**Comment by fagg** [comment]
I think this is resolved? :-)
