### ISSUE TITLE
mexw64 dependency issues

### ISSUE THREAD

**Issue by tgurtler** [fagg/matlab-zmq#33]
I'm using the master check out. I am able to run "make('build')" with the following result:

Building with 'MinGW64 Compiler (C)'.
MEX completed successfully.

Succesful build for:
    ZMQ_INCLUDE_PATH = C:\Program Files\ZeroMQ 4.0.4\include
    ZMQ_LIB_PATH = C:\Program Files\ZeroMQ 4.0.4\lib\
    ZMQ_COMPILED_LIB = libzmq-v120-mt-4_0_4.lib

ans =

```
 1
```

When I try to run "make('test')" the dll dependencies are not loading. I get the following error:
Invalid MEX-file 'C:\Users<user>\Downloads\matlab-zmq-master\lib+zmq+core\ctx_new.mexw64'

The mexw64 files exist. Any idea as to how to fix this?

I'm running Matlab R2015b (64-bit) on Windows 10 (64-bit). Also running 64-bit ZMQ.

**Comment by abravalheri** [comment]
@tgurtler I seems a compiler issue. Unfortunately I do not have windows10 + Matlab2015 here to try to replicate the environment. Have you ever compiled other mex files and get a different response? The test in documentation should work properly: http://www.mathworks.com/help/matlab/matlab_external/install-mingw-support-package.html

This issue may be related to the following [information](http://www.mathworks.com/help/matlab/matlab_external/compiling-c-mex-files-with-mingw.html):
```
If you use the MinGW compiler to build a MEX file that links to a library compiled with a non-MinGW compiler, such as Microsoft® Visual Studio®, the file will not run in MATLAB®. Library (.lib) files generated by different compilers are not compatible with each other.

You can generate a new library file using the dlltool utility from MinGW.
```

I'm not shure, but I think ZeroMQ uses Visual Studio® to build the distributable package. You can try exporting the lib, or compile ZMQ itself with MinGW.

The project https://github.com/Alexpux/MINGW-packages has a build script for ZMQ with MinGW-64 in the [msys2](https://msys2.github.io/) environment.

**Comment by fagg** [comment]
As far as I'm aware, nobody has tried to build this package with MinGW. As long as you have Mex set up for MinGW and ZMQ can be compiled using ZMQ, I do not see why this wouldn't work. However, I don't know whether either of these is possible so I can't really help.

Visual Studio, however, should not be a problem - and that's what I suggest people use if they need to build on Windows.

**Comment by darylsmit** [comment]
I have the same issue on:

-matlab 2016a
-compiler Visual Studio 2015

Did you get things up and running?

**Comment by darylsmit** [comment]
Sorry, fixed the problem by adding C:\Program Files\ZeroMQ 4.0.4\bin to the system path

**Comment by DzungTmd** [comment]
Hello,

I'm trying to install matlab-zmq on Ubuntu 14.04 with matlab 2015a, compiler gcc.
It showed: "MEX completed successfully." for all steps except the last step:

Errors during build for:
	ZMQ_INCLUDE_PATH = /usr/local/include/
	ZMQ_LIB_PATH = /usr/local/lib/
	ZMQ_COMPILED_LIB = libzmq.a
ans =

     0

Do you have any idea what is wrong, and how can I fix it? Thank you.

**Comment by tgurtler** [comment]
Try opening another issue that's for linux.
