### ISSUE TITLE
Error using zmq.core.ctx_new

### ISSUE THREAD

**Issue by ghost** [fagg/matlab-zmq#36]

**Comment by ghost** [comment]
Hi! I'm new on this protocol and need to extract data from a device via zeromq. I tried to run the script but end in this type of errors:

Error using zmq.core.ctx_new
Attempt to execute SCRIPT ctx_new as a function:
/Users/seba/Documents/MATLAB/PupilLabs/matlab-zmq-master/lib/+zmq/+core/ctx_new.m

Can you give me a hand?

Thanks!
Seba.

**Comment by abravalheri** [comment]
Hi @SebastianAusili, did you find out?

Maybe it was a compilation error...
