### ISSUE TITLE
creating mex file 

### ISSUE THREAD

**Issue by Marslanali** [fagg/matlab-zmq#38]
To run the make.m file. First we have to configure mex as mentioned on the instruction. But I am slightly confused how to do this in this case. After googling and spending hours, I still don't have any clue.  

Any insight ?

**Comment by joeyo** [comment]
https://www.mathworks.com/help/matlab/matlab_external/what-you-need-to-build-mex-files.html

**Comment by fagg** [comment]
"Ensure you have mex configured" means you need to have a working mex compiler on the machine. No special configuration required. Unless you have a specific question, I will close this.
