### ISSUE TITLE
Invalid MEX-file error

### ISSUE THREAD

**Issue by Marslanali** [fagg/matlab-zmq#39]
Hello,

I am using matlab 2016a and visual studio 2010. I run config.m file and all mex file are successfully build. When I run the examples code. I got the following error: 
 
Invalid MEX-file 'R:\Python_C++_Development\MATLAB\matlab-zmq\lib\+zmq\+core\ctx_new.mexw64': The specified module could not
be found.

Though I've added  lib directory in my MATLAB path. 

Any help ?

Thanks in advance

**Comment by amit1634** [comment]
Hi, I have a similar error. How did you resolve this issue? (Thanks)

**Comment by Marslanali** [comment]
> Hi, I have a similar error. How did you resolve this issue? (Thanks)

Hi,

I did this long time ago, however if you will attached the brief error which you are getting I will try to look into it and answer.

Also make sure you have C/C++ compiler enable on your OS. For instance on matlab you can check this by typing **mex -setup**. Attached is a screenshot of my matlab on linux.

![mex](https://user-images.githubusercontent.com/19324754/79610768-9eb0c200-8112-11ea-85ff-9261d8ac5bde.png)

Best,
Arslan

**Comment by amit1634** [comment]
Thanks Arslan, for your quick response. Luckily, I was able to fix all issues a couple hours after writing my previous comment. 
Cheers!

**Comment by Marslanali** [comment]
> Thanks Arslan, for your quick response. Luckily, I was able to fix all issues a couple hours after writing my previous comment.
> Cheers!

Sounds great. 

Arslan

**Comment by Zahra-on-Github** [comment]
> Thanks Arslan, for your quick response. Luckily, I was able to fix all issues a couple hours after writing my previous comment.
> Cheers!

Hi Amit, 
Can you please let me know how you fixed the issue? 
I get the exact same error.
